name: Send Weekly Email
on:
  schedule:
    - cron: "0 10 * * 1" # Weekly on Mondays at 10:00 AM UTC
  workflow_dispatch:     # Allows manual triggering
jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST Request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://outono.org/api/send'
          method: 'POST'
          headers: |
            Content-Type: application/json
            Authorization: Bearer ${{ secrets.API_SECRET_KEY }}
          data: '{}'
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
