name: Send Weekly Email

on:
  schedule:
    - cron: "0 10 * * 1" # Weekly on Mondays at 10:00 AM UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST Request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://outono.org/api/send'
          method: 'POST'
          data: '{"key": "value"}' # Optional: add JSON data if your API requires it
          headers: 'Content-Type: application/json' # Adjust content type as needed
          # Add any additional headers or authentication if required (e.g., Authorization: Bearer <token>)
